### ISSUE TITLE
make main right part clickable while offcanvas menu opened

### ISSUE THREAD

**Issue by astomas** [takaneichinose/bootstrap-off-canvas#1]
Being new to bootstrap, I'd like to customize your code in order to make all html items on the right side of the page (main section) still clickable while offcanvas menu is opened on the left side. How can I do, if I use a local customized version of your dev?
It would imply to close the offcanvas menu only by clicking on the toggle icon top left, but I dont mind.
Thx

**Comment by takaneichinose** [comment]
@astomas 
Hi, if you would look at line 28 of ```bootstrap-off-canvas.js```, there is a click event for ```off-canvas-content``` class, which is the right side of the page. If you would modify my code, you may just remove that event. I would also edit this source code to make this clickable thing optional.

Edit:

I just edited the source code. You may just update your source code using the latest JavaScript code of this repository.

Please tell me if there is another problem regarding this thing. Thank you.

Edit 2:

Don't forget to update the CSS file.

**Comment by astomas** [comment]
Great! works perfect with this new option, thanks a lot
