### ISSUE TITLE
slide over content instead of pushing it

### ISSUE THREAD

**Issue by astomas** [takaneichinose/bootstrap-off-canvas#2]
Hi, 
is there a way to make offcanvas menu slide over the main content when activated instead of pushing it to the right? I've tried setting overflow-x to visible in css with no luck.
If it's possible, how to make it slide just under the header?
Thx

**Comment by takaneichinose** [comment]
hi @astomas 
Hi, I can make an option to do that. I'm gonna let you know after I finished doing so.

**Comment by astomas** [comment]
thank you!

**Comment by takaneichinose** [comment]
@astomas 
I added the new feature: You may add ```is-float``` class to ```off-canvas``` to prevent the content to be pushed

**Comment by astomas** [comment]
Thank you. I've tried adding it like this : 
<div class="off-canvas is-float" data-target="#offcanvasid">
	<div class="off-canvas-wrapper">
		<div id="offcanvasid" class="off-canvas">	
....

I must be doing it wrong because there is no change

**Comment by astomas** [comment]
thank you, I've tried adding it like this but nothing has changed:
div class="off-canvas is-float" data-target="#offcanvasid"
  div class="off-canvas-wrapper"
    div id="offcanvasid" class="off-canvas"
      ...

**Comment by takaneichinose** [comment]
@astomas hi, thank you for commenting. I just changed how things works for floating off-canvas.

I added it into the readme file but here's how it works now

```HTML
<div id="off_canvas" class="off-canvas off-canvas-floating">
  <!-- Just use the default Bootstrap color utility here -->
  <div class="off-canvas-nav bg-dark">
    <!-- You may use any of the bootstrap components here -->
    <div class="nav nav-pills nav-fill flex-column">
      <a href="#" class="text-left nav-item nav-link active">Link 1</a>
        <a href="#" class="text-left nav-item nav-link">Link 2</a>
        <a href="#" class="text-left nav-item nav-link disabled">Disabled Link</a>
    </div>
  </div>
</div>
<!-- Your usual Bootstrap code goes here -->
<a href="#" class="off-canvas-toggler" type="button" data-target="#offcanvasid" aria-controls="offcanvasSupportedContent" aria-expanded="false" aria-label="Toggle off canvas menu">Toggle off canvas</a>
<div class="container">
  ...
</div>
```

Before, your bootstrap content is inside the ```off-canvas-content```. You should put it outside ```off-canvas``` div element.
You should also take out the ```off-canvas``` class outside the ```off-canvas-wrapper``` then add ```off-canvas-floating``` class into ```off-canvas```.

Don't forget to update your codebase.

**Comment by astomas** [comment]
it now works but is seems the off-canvas-no-close option is now always active (even when not called). Is that normal ?
It makes it difficult to close the menu (you have to find a non linkable area) and the toggle link is now hidden when positionned left in the header. Maybe an icon cross to close inside the offcanvas menu would help?

**Comment by takaneichinose** [comment]
@astomas hi, I can make it something like you can close the menu when you click the content.

**Comment by takaneichinose** [comment]
@astomas you can also add a close button at the top of the menu. Something like this:
‘‘’HTML

       <button class="btn btn-dark mb-2 off-canvas-toggler" type="button" data-target="#off_canvas" aria-controls="offcanvasSupportedContent" aria-expanded="false" aria-label="Toggle off canvas menu">
          <span aria-hidden="true">&times;</span> Close
        </button>
‘‘‘

**Comment by astomas** [comment]
yes! i will make it an clickable cross icon instead but it is now good. Is the off-canvas-no-close option being always active in your sample too?

**Comment by takaneichinose** [comment]
@astomas Yes, it's always active currently
